apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: spring-boot-sample
  name: spring-boot-sample
spec:
  selector:
    matchLabels:
      run: spring-boot-sample
  template:
    replicas: 4
    metadata:
      labels:
        run: spring-boot-sample
    spec:
      containers:
      - image: ${image}
        name: nginx